export default {
  "login": "andrehardy",
  "id": 74989379,
  "node_id": "MDQ6VXNlcjc0OTg5Mzc5",
  "avatar_url": "https://avatars0.githubusercontent.com/u/74989379?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/andrehardy",
  "html_url": "https://github.com/andrehardy",
  "followers_url": "https://api.github.com/users/andrehardy/followers",
  "following_url": "https://api.github.com/users/andrehardy/following{/other_user}",
  "gists_url": "https://api.github.com/users/andrehardy/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/andrehardy/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/andrehardy/subscriptions",
  "organizations_url": "https://api.github.com/users/andrehardy/orgs",
  "repos_url": "https://api.github.com/users/andrehardy/repos",
  "events_url": "https://api.github.com/users/andrehardy/events{/privacy}",
  "received_events_url": "https://api.github.com/users/andrehardy/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Andre Hardy",
  "company": "Self-Employed",
  "blog": "andrehardy.github.io",
  "location": "Central PA",
  "email": null,
  "hireable": null,
  "bio": "Software Developer with a love for design",
  "twitter_username": "andre_hardy77",
  "public_repos": 4,
  "public_gists": 0,
  "followers": 31,
  "following": 11,
  "created_at": "2020-11-24T20:28:27Z",
  "updated_at": "2021-01-12T15:40:02Z"
}